#!/bin/sh

# Colors
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;33m'

echo "\n${BBlue}Installing .git/hooks${NC}"
sh -c "$(curl -fsSl https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/hooks/run)"

echo "\n${BRed}Do you want to install the PHP Verification Tools? (Y for yes or N for no)${NC}"
read PHPPACKAGES

echo "\n${BBlue}Installing workspace directory${NC}"
if [ ! -d './workspace' ]
then
    mkdir ./workspace
    echo "*
!.gitignore" > ./workspace/.gitignore
fi

echo "\n${BBlue}All done! 😎${NC}"
