name: Deployment Notifications

on:
  push:
    branches: master

jobs:
  update-available:
    name: "Update Available"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Slack Started Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Actions
          SLACK_COLOR: "good"
          SLACK_ICON: "https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/.github/workflows/devsquad-logo.png"
          SLACK_TITLE: "Update Available"
          SLACK_MESSAGE: "Our setup workflow was updated, please run the command ```sh -c "$(curl -fsSL https://raw.githubusercontent.com/elitedevsquad/devsquad-setup/master/run)"``` to update your local environment."
